# Generated by Django 4.2.2 on 2023-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_experience_for_clients_header_infos_initials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emojy', models.TextField(blank=True, max_length=30, null=True)),
                ('title', models.IntegerField()),
                ('subtitle', models.TextField()),
            ],
        ),
    ]
