# Generated by Django 4.2.2 on 2023-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_countbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='countbox',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countbox',
            name='title',
            field=models.TextField(),
        ),
    ]
