# Generated by Django 4.2.2 on 2023-07-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_countbox_count_alter_countbox_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountBox',
            new_name='Count_Box',
        ),
    ]
