# Generated by Django 4.2.2 on 2023-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_initials_user_skill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='short_description',
            field=models.TextField(max_length=80),
        ),
    ]
