# Generated by Django 4.2.2 on 2023-07-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.TextField(max_length=50)),
                ('iconas', models.CharField(max_length=20)),
            ],
        ),
    ]
