# Generated by Django 4.2.2 on 2023-08-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_sociallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
