# Generated by Django 4.2.2 on 2023-08-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_experience_end_date_alter_experience_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summery',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
