# Generated by Django 4.2.2 on 2023-08-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_alter_summery_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=15)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
    ]
